"use server";
import { and, eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/db";
import { billPayments, bills, debtPayments, debts, user } from "@/db/schema";
import { requireAuth } from "@/lib/auth/require-auth";
const money=z.coerce.number().int().min(1).max(2_147_483_647); const bill=z.object({name:z.string().min(1),amount:money,dueDay:z.coerce.number().int().min(1).max(31),category:z.string().min(1),notes:z.string().optional()}); const debt=z.object({name:z.string().min(1),lender:z.string().min(1),originalAmount:money,remainingAmount:money,installmentAmount:money,dueDay:z.coerce.number().int().min(1).max(31),notes:z.string().optional()});
async function owner(){await requireAuth();const email="local@myfinance.private";const row=await db.select().from(user).where(eq(user.email,email)).limit(1);if(row[0])return row[0].id;return (await db.insert(user).values({email,name:"MyFinance owner",emailVerified:true}).returning())[0].id} const done=()=>{revalidatePath("/bills");revalidatePath("/dashboard")};
export async function createBill(f:FormData){const d=bill.parse(Object.fromEntries(f));await db.insert(bills).values({...d,userId:await owner(),frequency:"monthly"});done()}
export async function deleteBill(f:FormData){const id=z.string().uuid().parse(f.get("id"));await requireAuth();await db.delete(bills).where(eq(bills.id,id));done()}
export async function markBillPaid(f:FormData){const id=z.string().uuid().parse(f.get("id"));const userId=await owner();const [b]=await db.select().from(bills).where(and(eq(bills.id,id),eq(bills.userId,userId)));if(!b)throw new Error("Bill not found");const month=new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit"}).format(new Date())+"-01";await db.insert(billPayments).values({userId,billId:id,billingMonth:month,amount:b.amount,dueDate:`${month.slice(0,7)}-${String(b.dueDay).padStart(2,"0")}`,paidAt:new Date(),status:"paid"}).onConflictDoUpdate({target:[billPayments.billId,billPayments.billingMonth],set:{paidAt:new Date(),status:"paid"}});done()}
export async function createDebt(f:FormData){const d=debt.parse(Object.fromEntries(f));if(d.remainingAmount>d.originalAmount)throw new Error("Remaining exceeds original");await db.insert(debts).values({...d,userId:await owner(),debtType:"other"});done()}
export async function deleteDebt(f:FormData){const id=z.string().uuid().parse(f.get("id"));await requireAuth();await db.delete(debts).where(eq(debts.id,id));done()}
export async function recordDebtPayment(f:FormData){const id=z.string().uuid().parse(f.get("id"));const amount=money.parse(f.get("amount"));const userId=await owner();await db.transaction(async tx=>{const [d]=await tx.select().from(debts).where(and(eq(debts.id,id),eq(debts.userId,userId)));if(!d)throw new Error("Debt not found");if(d.remainingAmount<=0)throw new Error("Debt is already paid off");const paid=Math.min(amount,d.remainingAmount);await tx.insert(debtPayments).values({userId,debtId:id,amount:paid,principalAmount:paid,paidAt:new Date().toISOString().slice(0,10)});await tx.update(debts).set({remainingAmount:d.remainingAmount-paid,status:d.remainingAmount===paid?"paid":"active"}).where(eq(debts.id,id))});done()}
