"use server";
import { and, eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/db";
import { goals, user } from "@/db/schema";
import { requireAuth } from "@/lib/auth/require-auth";
const money=z.coerce.number().int().min(0).max(2_147_483_647);const goal=z.object({name:z.string().min(1),targetAmount:money.refine(n=>n>0),currentAmount:money,targetDate:z.string().optional(),priority:z.coerce.number().int().min(1).max(3)});async function owner(){await requireAuth();const email="local@myfinance.private";const r=await db.select().from(user).where(eq(user.email,email)).limit(1);if(r[0])return r[0].id;return(await db.insert(user).values({email,name:"MyFinance owner",emailVerified:true}).returning())[0].id}const done=()=>{revalidatePath("/goals");revalidatePath("/dashboard")};
export async function createGoal(f:FormData){const d=goal.parse(Object.fromEntries(f));if(d.currentAmount>d.targetAmount)throw new Error("Current amount exceeds target");await db.insert(goals).values({userId:await owner(),name:d.name,goalType:"other",targetAmount:d.targetAmount,currentAmount:d.currentAmount,targetDate:d.targetDate||null,priority:d.priority,status:d.currentAmount===d.targetAmount?"completed":"active"});done()}
export async function updateGoal(f:FormData){const id=z.string().uuid().parse(f.get("id"));const d=goal.parse(Object.fromEntries(f));if(d.currentAmount>d.targetAmount)throw new Error("Current amount exceeds target");const userId=await owner();await db.update(goals).set({...d,targetDate:d.targetDate||null,status:d.currentAmount===d.targetAmount?"completed":"active"}).where(and(eq(goals.id,id),eq(goals.userId,userId)));done()}
export async function addGoalProgress(f:FormData){const id=z.string().uuid().parse(f.get("id"));const amount=z.coerce.number().int().min(1).parse(f.get("amount"));const userId=await owner();const [g]=await db.select().from(goals).where(and(eq(goals.id,id),eq(goals.userId,userId)));if(!g||g.currentAmount+amount>g.targetAmount)throw new Error("Contribution exceeds remaining amount");await db.update(goals).set({currentAmount:g.currentAmount+amount,status:g.currentAmount+amount===g.targetAmount?"completed":"active"}).where(eq(goals.id,id));done()}
export async function deleteGoal(f:FormData){const id=z.string().uuid().parse(f.get("id"));const userId=await owner();await db.delete(goals).where(and(eq(goals.id,id),eq(goals.userId,userId)));done()}
